### ISSUE TITLE
Elastic Search Not working on Windows System

### ISSUE THREAD

**Issue by rishi1117** [shelfio/jest-elasticsearch#59]
I am getting issues while using this module on my system. I am having windows system. Is windows not supported for this package to function ? 

(node:6612) UnhandledPromiseRejectionWarning: Error: Unsupported OS, try run on OS X or Linux
    at getVersionSuffix (C:\Users\rishi.saini\Desktop\Litera.CAM.cam-requestWorkflow\lib\node_modules\@shelf\elasticsearch-local\lib\index.js:189:15)
    at start (C:\Users\rishi.saini\Desktop\Litera.CAM.cam-requestWorkflow\lib\node_modules\@shelf\elasticsearch-local\lib\index.js:53:44)
    at func (C:\Users\rishi.saini\Desktop\Litera.CAM.cam-requestWorkflow\lib\elastic-start.js:14:27)
    at Object.<anonymous> (C:\Users\rishi.saini\Desktop\Litera.CAM.cam-requestWorkflow\lib\elastic-start.js:20:1)

**Comment by rishi1117** [comment]
My elastic search version is 7.10.2
